
services:
   evolution:
    image: evoapicloud/evolution-api:v2.3.4
    depends_on:
      - database
      - redis
    volumes:
      - evolution_data:/evolution/instances
    networks:
      - chatwave
    environment:
      - SERVER_URL=${SERVER_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_BAILEYS=${LOG_BAILEYS}
      - DEL_INSTANCE=false
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${SERVICE_NAME}_database:5432/${SERVICE_NAME}?connection_limit=40&pool_timeout=30&idle_timeout=5000
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      - DATABASE_CONNECTION_CLIENT_NAME=${SERVICE_NAME}
      - RABBITMQ_ENABLED=true
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RABBITMQ_EXCHANGE_NAME=${SERVICE_NAME}
       - SQS_ENABLED=false
      - SQS_ACCESS_KEY_ID=
      - SQS_SECRET_ACCESS_KEY=
      - SQS_ACCOUNT_ID=
      - SQS_REGION=
      - WEBSOCKET_ENABLED=false
      - WEBSOCKET_GLOBAL_EVENTS=false
      - WA_BUSINESS_TOKEN_WEBHOOK=evolution
      - WA_BUSINESS_URL=https://graph.facebook.com
      - WA_BUSINESS_VERSION=v20.0
      - WA_BUSINESS_LANGUAGE=pt_BR
      - WEBHOOK_GLOBAL_URL=''
      - WEBHOOK_GLOBAL_ENABLED=false
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
      - WEBHOOK_EVENTS_APPLICATION_STARTUP=false
      - WEBHOOK_EVENTS_QRCODE_UPDATED=true
      - WEBHOOK_EVENTS_MESSAGES_SET=true
      - WEBHOOK_EVENTS_MESSAGES_UPSERT=true
      - WEBHOOK_EVENTS_MESSAGES_EDITED=true
      - WEBHOOK_EVENTS_MESSAGES_UPDATE=true
      - WEBHOOK_EVENTS_MESSAGES_DELETE=true
      - WEBHOOK_EVENTS_SEND_MESSAGE=true
      - WEBHOOK_EVENTS_CONTACTS_SET=true
      - WEBHOOK_EVENTS_CONTACTS_UPSERT=true
      - WEBHOOK_EVENTS_CONTACTS_UPDATE=true
      - WEBHOOK_EVENTS_PRESENCE_UPDATE=true
      - WEBHOOK_EVENTS_CHATS_SET=true
      - WEBHOOK_EVENTS_CHATS_UPSERT=true
      - WEBHOOK_EVENTS_CHATS_UPDATE=true
      - WEBHOOK_EVENTS_CHATS_DELETE=true
      - WEBHOOK_EVENTS_GROUPS_UPSERT=true
      - WEBHOOK_EVENTS_GROUPS_UPDATE=true
      - WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE=true
      - WEBHOOK_EVENTS_CONNECTION_UPDATE=true
      - WEBHOOK_EVENTS_LABELS_EDIT=true
      - WEBHOOK_EVENTS_LABELS_ASSOCIATION=true
      - WEBHOOK_EVENTS_CALL=true
      - WEBHOOK_EVENTS_TYPEBOT_START=false
      - WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS=false
      - WEBHOOK_EVENTS_ERRORS=false
      - WEBHOOK_EVENTS_ERRORS_WEBHOOK=
      - CONFIG_SESSION_PHONE_CLIENT=Windows
      - CONFIG_SESSION_PHONE_NAME=Chrome
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1027171458
      - QRCODE_LIMIT=30
      - OPENAI_ENABLED=true
      - DIFY_ENABLED=true
      - TYPEBOT_ENABLED=true
      - TYPEBOT_API_VERSION=latest
      - CHATWOOT_ENABLED=true
      - CHATWOOT_MESSAGE_READ=true
      - CHATWOOT_MESSAGE_DELETE=true
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=${CHATWOOT_IMPORT_DATABASE_CONNECTION_URI}
      - CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE=true
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://${SERVICE_NAME}_redis:6379/1
      - CACHE_REDIS_PREFIX_KEY=${SERVICE_NAME}
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
      - S3_ENABLED=${S3_ENABLED}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PORT=443
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_USE_SSL=true
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - LANGUAGE=en
      - SENTRY_DSN=${SENTRY_DSN}
      - CHATWOOT_BOT_CONTACT=false
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: "2"
          memory: 4096M
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST}`)
        - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
        - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencryptresolver
        - traefik.http.routers.${SERVICE_NAME}.priority=1
        - traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}
        - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080
        - traefik.http.services.${SERVICE_NAME}.loadbalancer.passHostHeader=true
   database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - TZ=America/Sao_Paulo
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    networks:
      - chatwave
   
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 4G
          
   redis:
      image: redis:latest
      command: [
          "redis-server",
          "--appendonly",
          "yes",
          "--port",
          "6379"
        ]
      volumes:
        - redis_data:/data
      networks:
        - chatwave
      deploy:
        placement:
          constraints:
            - node.role == manager
        resources:
          limits:
            cpus: "1"
            memory: 512M

volumes:
  evolution_data:
    external: true
    name: ${SERVICE_NAME}_data
  postgres_data:
    external: true
    name: ${SERVICE_NAME}_database
  redis_data:
    external: true
    name: ${SERVICE_NAME}_cache_v2

networks:
  chatwave:
    external: true
    name: chatwave
